### PR TITLE
Set target to ES5

### PR DESCRIPTION
**Pull request by gksander**
This PR drops compile target to ES5.

### CODE REVIEW

**Review by ljharb — DISMISSED** [review]
Before the first release it'd be great to add a testing matrix :-)

**Comment by gksander** [comment]
@ljharb What's the best way to do this? Add to our existing Node matrix for our lint/test workflow, or add a new workflow to test the compiled code?

**Comment by ljharb** [comment]
Which existing test matrix?

**Comment by gksander** [comment]
Our current "CBPay-JS tests" job runs on a Node matrix, [see here](https://github.com/coinbase/cbpay-js/blob/fdc943eb73cb05990cc7b795717800b59ca797ac/.github/workflows/static-analysis.yml#L9-L11)

**Comment by ljharb** [comment]
ahhh gotcha, "static-analysis" confused me :-)

i'd suggest making the lint job only run once, and putting the tests (which aren't static analysis) in a separate workflow that runs on all supported node versions. I have some shared workflows you can use to make it easy.

**Review by ljharb — APPROVED** [review]

**Comment by gksander** [comment]
Nice, that's good feedback – I'll follow up with that.

**Pull request merged**
