### PR TITLE
[meta] update package.json, actions

### PR DESCRIPTION
**Pull request by ljharb**

### CODE REVIEW

**Comment by ljharb** [comment]
node 18 is broken due to https://github.com/nodejs/node/issues/42638#issuecomment-1105543393, so i'm going to make it an allowed failure for now.

**Comment by ljharb** [comment]
Unfortunately, continue-on-error shows up this way - as failures on "not the required" checks

**Review by gksander — APPROVED** [review]
Nice.

**Comment by ljharb** [comment]
update one more time to add a "everything's done" job after the matrix is finished

**Review by gksander — APPROVED** [review]

**Review by Jphaphon1 — COMMENTED** [review]
Fix

**Pull request merged**
